#!/usr/bin/env python
import sys

assert(len(sys.argv) == 2)

print("Graph show {")

for line in open(sys.argv[1]):
  a = line.split(" ")
  if a[0] == 'V':
    print("\t v%i;" % int(a[1]))
  elif a[0] == 'E':
    print("\t v%i -- v%i [label=\"%i\"]" % (int(a[1]), int(a[2]), int(a[3])))

print("}")
