heur: design.bib heur.tex
	pdflatex heur.tex

p: hpres.tex
	pdflatex hpres.tex

design:	design.bib
	pdflatex design.tex

pres: design.bib
	pdflatex presdesign.tex

design.bib:
	pdflatex design.tex
	bibtex design
	pdflatex design.tex


